#dubbo配置
spring:
  application:
    name: lottery-pay-provider
  datasource:
    druid:
      url: jdbc:mysql://meyasy.com:3306/pay?useUnicode=true&characterEncoding=utf8&useOldAliasMetadataBehavior=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
      username: root
      password: Rm3/w7v678k7mjklZnemgqGqTQKCIjPwUhq11o6d08q7XljtFeLI249X93J0XpUCMQHykqJ0R4OYZGy67ES4EQ==
      initial-size: 2
      min-idle: 1
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat:
        enabled: true
        log-slow-sql: true
        slow-sql-millis: 1000
      config:
        enabled: true
        key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAKCsI4jDrxfxZAiGqiaJJVevyHA2o05CHM7J3iFb2vcpd5wYhrefu8rfjQzS0AloTDCuop+FoB4U8WlAbjvEblcCAwEAAQ==
      max-pool-prepared-statement-per-connection-size: 20
dubbo:
  application:
    id: lottery-pay-provider
    name: lottery-pay-provider
    owner: meyasy
  registry:
    address: meyasy.com:2181
    id: lottery-pay-provider-registry
    protocol: zookeeper
    group: lottery-pay-provider
    file: /logs/cache/pay-service.cache
  protocol:
    id: dubbo
    name: dubbo
    port: 20881
    accesslog: /logs/dubbo-pay.log
  scan:
    basePackages: com.meyasy.pay.services
lottery:
  user:
    service:
      version:  1.0.0
#mybatis:
#  type-aliases-package: com.meyasy.user.entity
#  mapper-locations: classpath*:com\meyasy\user\persistence\mapper\*.xml
#  configuration:
#    jdbc-type-for-null: null






