spring:
  application:
    name: lottery-sso
  kaptcha:
    properties:
      kaptcha.border: 'no'
      kaptcha.border.color: 105,179,90
      kaptcha.textproducer.font.color: blue
      kaptcha.image.width: "125"
      kaptcha.image.height: "45"
      kaptcha.textproducer.font.size: "45"
      kaptcha.textproducer.char.length: "4"
      kaptcha.textproducer.font.names: 宋体,楷体,微软雅黑
dubbo:
  application:
    id: lottery-sso
    name: lottery-sso
  protocol:
    id: dubbo
    name: dubbo
    port: 20880
  registry:
    protocol: zookeeper
    port: 2181
    address: meyasy.com
    group: lottery-user-provider
    id: lottery-user-provider-registry
lottery:
  user:
    service:
      version:  1.0.0
server:
  port: 8081
kaptcha:
  border: no
  textproducer:
    font:
      color: 105,179,90
      size: 45
      names: 宋体,楷体,微软雅黑
    char:
      length: 4

  image:
    width: 125
    height: 45

